// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjVZWsiq077YWEzGLtXXISuQAr5YviNYM',
    appId: '1:480503602213:web:c044403f5e12415af373cc',
    messagingSenderId: '480503602213',
    projectId: 'sneaker-shop-e6720',
    authDomain: 'sneaker-shop-e6720.firebaseapp.com',
    storageBucket: 'sneaker-shop-e6720.firebasestorage.app',
    measurementId: 'G-6PF8VRDRR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBTnlLLG4G29RtodYA15acrdQ5OeKCmuk',
    appId: '1:480503602213:android:bcdef09b2716e725f373cc',
    messagingSenderId: '480503602213',
    projectId: 'sneaker-shop-e6720',
    storageBucket: 'sneaker-shop-e6720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33-sfx5FlQ1WzmleA8nrhiFHEKFn83Wo',
    appId: '1:480503602213:ios:de5fc03466fdbd1df373cc',
    messagingSenderId: '480503602213',
    projectId: 'sneaker-shop-e6720',
    storageBucket: 'sneaker-shop-e6720.firebasestorage.app',
    iosBundleId: 'com.example.sneakerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33-sfx5FlQ1WzmleA8nrhiFHEKFn83Wo',
    appId: '1:480503602213:ios:de5fc03466fdbd1df373cc',
    messagingSenderId: '480503602213',
    projectId: 'sneaker-shop-e6720',
    storageBucket: 'sneaker-shop-e6720.firebasestorage.app',
    iosBundleId: 'com.example.sneakerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjVZWsiq077YWEzGLtXXISuQAr5YviNYM',
    appId: '1:480503602213:web:1474b799a935d7c6f373cc',
    messagingSenderId: '480503602213',
    projectId: 'sneaker-shop-e6720',
    authDomain: 'sneaker-shop-e6720.firebaseapp.com',
    storageBucket: 'sneaker-shop-e6720.firebasestorage.app',
    measurementId: 'G-R02LFSV69Y',
  );
}
